### ISSUE TITLE
Final Google Docs Migration Plan

### ISSUE THREAD

**Issue by c-mart** [access-ci-org/Integration_Roadmaps#18]
- [x] April 7, subteam should have a draft of change management documentation
- [x] April 10, migration day
  - [x] Migrate Google documents to GitHub
  - [ ] Restrict Google docs permission
  - [x] Place a banner at the top of each Google Doc, linking to [new ReadTheDocs site](https://readthedocs.access-ci.org/)
- [x] By April 14, apply queued GitHub issues that can only by applied in GitHub
  - #5, #11, #12, #13
- [x] Cleanup of external links to Integration Roadmaps to point to [new ReadTheDocs site](https://readthedocs.access-ci.org/)

**Comment by jpnavarro** [comment]
From: "Navarro, JP" <...>
Subject: FREEZE ACCESS Integration Roadmap Google documentation
Date: April 11, 2023 at 9:46:45 AM CDT
To: "Haney, Jess" <...>, Liming Lee <...>, Nathan Tolbert <...>, Chris Martin <...>, "White, Joseph" <...>, Quick Rob <...>, "hackworth@psc.edu" <...>, Kathy Benninger <...>, "Wheeler, David" <...>, Shane Filus <...>, Alana Romanella <...>, Jennifer Schopf <...>, Ruth Marinshaw <...>

ACCESS Integration Roadmap documentation authors and coordinators:

This week we are migrating our integration roadmaps Google documents to GitHub + ReadTheDocs.

PLEASE do not update any of these Google documents effective today.

Early on Wednesday April 12, 2023 we will run the final Google docs to GitHub conversion. After that, changes to Google documents will be lost. We will place a banner in Google documents reminding you that the document are no longer official and referencing the new GitHub repository. We will also try to restrict Google document updates.

When we are ready to start accepting updates in GitHub later this week we will email you documentation on how to do updates.

Thanks,

- JP, Jess, Chris M, Rob Q, and Anu
— Google to GitHub transition sub-team

**Comment by jpnavarro** [comment]
April 14 tasks and external cleanup aren't done.

**Comment by mollycule** [comment]
Looks like the April 14 tasks are complete.

What (if any) external links are needing to be updated?

**Comment by jpnavarro** [comment]
change management document marked as complete because we split it out into a separate issue #29

**Comment by jpnavarro** [comment]
JP reminded track contacts to fix any external references to the obsolete roadmap Google documents. Marking the cleanup as done.

**Comment by jpnavarro** [comment]
JP reminded track contacts to fix any external references to the obsolete roadmap Google documents. Marking the cleanup as done. As this is the last sub-task, closing this issue.
