### ISSUE TITLE
Make the primary index.rst doctree only display the roadmap descriptions and the tasks

### ISSUE THREAD

**Issue by jpnavarro** [access-ci-org/Integration_Roadmaps#7]

**Comment by mollycule** [comment]
I've created a readthedocs version that's "Active" and "Hidden", so it's accessible as long as the URL is known while not being obviously visible as an option for a regular end user. Here's the link: https://readthedocs.access-ci.org/projects/integration-roadmaps/en/mollycule-simplify-index.rst/
